### ISSUE TITLE
Mention of TypeScript types (@types/gm_config)

### ISSUE THREAD

**Issue by MysteryBlokHed** [sizzlemctwizzle/GM_config#101]
TypeScript types for GM_config are available through the DefinitelyTyped package [@types/gm_config](https://www.npmjs.com/package/@types/gm_config). It could be worth mentioning this in the wiki or somewhere for any TypeScript devs looking to use this library with typing support :)

**Comment by Martii** [comment]
Unless @sizzlemctwizzle added these, which is unlikely per past communication, it's not something that I've done. i.e. I'm guessing those are unofficial.

**Comment by MysteryBlokHed** [comment]
Yes, the types are unofficial.

The files on DefinitelyTyped aren't a re-implementation of this library; GM_config would still need to be `@require`'d. What the file contains are hints for the TypeScript compiler so that it knows what the signature of functions and objects are, like `GM_config.init`. This means that an error would be produced if, for example, a developer tries to pass a string where a number was expected. Without the original JavaScript library, the types are useless.

Code was modified from the MIT-licensed [GM_config unit tests](https://github.com/sizzlemctwizzle/UserScripts/blob/master/gm_config_unit_test.user.js) in [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gm_config/test/modified-original-unit-tests.ts) to test the types, where there’s a comment mentioning the original file’s license. I could add a clearer comment with the MIT license if it’s preferred. Other than that, no code was copied/modified from GM_config.

**Comment by Martii** [comment]
> What the file contains are hints for the TypeScript compiler so that it knows what the signature of functions and objects are, like 

Well aware of descriptive nature of .ts with any IDE.

>  could add a clearer comment with the MIT license if it’s preferred.

 and it still needs to be same licensed as the source. LGPL and all primary contributors must always be included in any file regardless of port/subset.

**Comment by MysteryBlokHed** [comment]
I don't see how the types would violate this project's LGPL.
As I said, the only code that was copied or modified from existing code was one of the tests, a modification of [an MIT-licensed file](https://github.com/sizzlemctwizzle/UserScripts/blob/cd509f92/gm_config_unit_test.user.js#L5). Anything else was written from scratch and *does not depend on or use code from GM_config*. This means that it is not an application using the library ([lines 22-25 of LGPL](https://github.com/sizzlemctwizzle/GM_config/blob/43fd0fe4/LICENSE#L22-L25)) nor a copy of the library.

It's fine, of course, if you don't want to mention the types package, but I don't think a DMCA is warranted.

**Comment by Martii** [comment]
> It's fine, of course, if you don't want to mention the types package, but I don't think a DMCA is warranted.

Mentioning has already been rejected. However I was giving you a chance to fix it before a DMCA is files and a possible TDN. Copyright infringement isn't a good thing and you did it with that commit. This is not up for negotiation. You've put yourself and that project in jeopardy and I would suggest that you fix it before the consequences roll down.

**Comment by MysteryBlokHed** [comment]
It seems like you keep replying to specific parts of my messages without acknowledging the important parts. I guess you can file your DMCA; maybe you'll explain what I've actually done more clearly to support than you did here.

**Comment by Martii** [comment]
Repeating what I've said before:

1) Any part or portion of this code is LGPL not MIT. You violated that by posting it elsewhere. It must stay LGPL.
2) You set the Copyright, whether intentionally or not, to Microsoft instead of what is listed at https://github.com/sizzlemctwizzle/GM_config/blob/master/LICENSE
3) Your circumvented the whole GitHub process of "Contributor" by not starting at this project itself. You should have started here not on some unofficial, foreign, project. Your etiquette is very questionable on anything.

If you remedied all of these we'll hold off off on the DMCA but you can't delay or I have the DMCA just about ready... plus then I can sponsor your contribution in the wiki here. Until then it is an illegal fork regardless that it's just a plain subtype description for IDEs which can be continued to be illegal if someone forks that project. You did a rather large no no in OSS/FOSS.

Please fix it very quickly under an act of good faith otherwise it will be deemed as an act of bad faith.

**Comment by Martii** [comment]
Reconciliation attempt at DefinitelyTyped/DefinitelyTyped#57221

**Comment by Martii** [comment]
Reconciliation attempt partially failed as a Microsoft managed project does not allow other licenses, individual ownership, and Copyright of other individuals work. i.e. not true FOSS but centralized governorship.

Closing per DefinitelyTyped/DefinitelyTyped#57261 merge status removal of GM_config TypeScripts and tests.

Please feel free to open a new issue on our open repository if you wish to proceed forward.

You did attribute @sizzlemctwizzle Unit Test in your source it was just unfortunate that we couldn't assist you here first. It is well written.
