### ISSUE TITLE
TypeScript Type Definitions

### ISSUE THREAD

**Issue by MysteryBlokHed** [sizzlemctwizzle/GM_config#102]
Since DefinitelyTyped didn't support LGPL and removed the types, I'd be willing to commit them to this repository copyright the GM_config contributors.

I could just add the definitions file to the root of the repository, or I could make a folder that contains the types and its tests? If there's a better way to do this, let me know.

**Comment by Martii** [comment]
Root would probably be best for a single file.

The way GNU works is you would also add yourself as well to this file at the top... first in first out *(FIFO)*. Easy as pie. :smile_cat: 

e.g.


``` js
/*
Copyright 2009+, GM_config Contributors (https://github.com/sizzlemctwizzle/GM_config)

GM_config Collaborators/Contributors:
    Mike Medley <medleymind@gmail.com>
    Joe Simmons
    Izzy Soft
    Marti Martz
    Adam Thompson-Sharpe 

GM_config is distributed under the terms of the GNU Lesser General Public License.
    GM_config is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
```

.... optionally an email if you wish. I usually use githubs no reply addy to protect myself from getting spammed but haven't done that yet for this.

**Comment by Martii** [comment]
LGPL header in every file you create too that can support it. This is how all is protected. JSON obviously can't but there could be a messy workaround since that spec doesn't support comments.
