### ISSUE TITLE
Select Multiple

### ISSUE THREAD

**Issue by CandiceJoy** [sizzlemctwizzle/GM_config#104]
multiple: true on a select field doesn't seem to work...am I a doofus?

**Comment by Martii** [comment]
I don't believe multiple select fields are supported through a quick skim of the source.

I don't see anything like it show up on the [demo page](https://sizzlemctwizzle.github.io/GM_config/).

**Comment by sizzlemctwizzle** [comment]
If this is possible, this behavior has never been supported. Given that doing this would be possible by creating a custom field that extends the existing, I don't seen value into adding such a feature into GMC itself.
