### ISSUE TITLE
Dynamically creating fields

### ISSUE THREAD

**Issue by chlorophylls** [sizzlemctwizzle/GM_config#105]
I've scoured the wiki and can't seem to find documentation or an example on how to programmatically create a new field. 

For instance, clicking a button to create a new text field, with certain default text, in a specific section such that it shows up underneath the other already-created fields in the config panel. Have I missed something?

**Comment by Azuzula** [comment]
I just make string and then parse it to JSON. Plain string does not work and I think we can't pass javascript code to JSON or I'm doing elementary mistake somewhere. :(
` 

        var myRows = 3; // or get row number from any field initialised before GM_config.get('rowsField');
        var myText = "{";
        for (var i = 1; i <= myRows; i++){
            var text =
                '"head'+i+'":{'+
                '"section": "Row '+i+'",'+
                '"labelPos": "left",'+
                '"options": ["odkaz", "čára"],'+
                '"label": "Odkaz, nebo oddělovací čára",'+
                '"type": "radio",'+
                '"default": "odkaz"'+
                '},'+
                '"url'+i+'":{'+
                '"labelPos": "left",'+
                '"label": "URL",'+
                '"type":"text",'+
                '"size":"60",'+
                '"default": "/admin/"'+
                '}';

            myText = myText + text;
            if(i < myRows){
                myText=myText+",";
            }
        };

        myText = myText + "}";
        var fieldDefs = JSON.parse(myText);

        GM_config.init(
            {
                'id': 'Settings', // The id used for this instance of GM_config
                'title': 'My Settings',
                'fields': fieldDefs, // Fields object
            });
`

**Comment by sizzlemctwizzle** [comment]
I actually ran into this use case myself and had to use a hack to get it working. This functionality will be included.

**Comment by sizzlemctwizzle** [comment]
How I'm going to implement this:
GM_config.init will append new fields to the frame if open. Add an onload event to fields so you can move these new fields to where you want them in the frame.

**Comment by sizzlemctwizzle** [comment]
Does not create new sections. Appends all new fields to the last section in the open frame. Use `close` and then `open` to do a full refresh of the frame.

**Comment by airtonix** [comment]
@sizzlemctwizzle can we get an example of what you're talking about?
