### ISSUE TITLE
Redefine save and close buttons?

### ISSUE THREAD

**Issue by aolko** [sizzlemctwizzle/GM_config#110]
Is it possible to redefine the save and close buttons to either rebinding them to a different element or just changing button text and title?

**Comment by TMD20** [comment]
read the wiki 
You can do it with the open event listener

It gives you access to the window that pops up

**Comment by aolko** [comment]
Can you provide a helpful snippet?

**Comment by sizzlemctwizzle** [comment]
read the wiki
