### ISSUE TITLE
`Object.create(null)` duplication

### ISSUE THREAD

**Issue by Martii** [sizzlemctwizzle/GM_config#117]
@sizzlemctwizzle 

This is in regards to https://github.com/sizzlemctwizzle/GM_config/issues/92#issuecomment-1556281822

Should:

https://github.com/sizzlemctwizzle/GM_config/blob/4534fbaa392c7f6b5e4b08efcfc374417128ce0f/gm_config.js#L552

be there since it's *(kindof)* already defined at:

https://github.com/sizzlemctwizzle/GM_config/blob/4534fbaa392c7f6b5e4b08efcfc374417128ce0f/gm_config.js#L589

... and ...

https://github.com/sizzlemctwizzle/GM_config/blob/4534fbaa392c7f6b5e4b08efcfc374417128ce0f/gm_config.js#L48

?

---

This might be one of those JSHint things that can't be resolved.

**Comment by sizzlemctwizzle** [comment]
I could have sworn I got rid of that line (552). But it's gone now.

**Comment by Martii** [comment]
It's okay... was a rough day *(at least for me)* yesterday and the day before. :)
