### ISSUE TITLE
opening config

### ISSUE THREAD

**Issue by nickythegreek** [sizzlemctwizzle/GM_config#31]
when I call the config to open  using GM_config.open(); and load the page, I get the config window just fine.

However, I cannot get the config window to open using the Grease Monkey User Scripts Commands area.

The line I am using is:
GM_registerMenuCommand("config open test", GM_config.open);

I see the "config open test" in the menu, but clicking on it does nothing.

**Comment by dartraiden** [comment]
Same error in Tampermonkey

`GM_registerMenuCommand('Configuration',GM_config.open`);

`Uncaught TypeError: this.create is not a function`
