### ISSUE TITLE
Demo page is blank!

### ISSUE THREAD

**Issue by alexandre-mbm** [sizzlemctwizzle/GM_config#64]
Firefox 29.0 on Ubuntu 12.04.4. LTS.

**Comment by Martii** [comment]
Closed by 9c49300 and 5606657

**Comment by jesus2099** [comment]
We have to install the user script so the demo works?
Maybe if so, please tell users to « please install user script before coming to this demo page » on the demo (blank) page itself.
I also get a blank page where I expected a demo. :)

**Comment by Martii** [comment]
@jesus2099 

> We have to install the user script so the demo works? 

It's optional... just click the url and it should pop up the DOM *(Content Scope)* usage of GMC. Sizzle fixed the GH io page references [around here](https://github.com/sizzlemctwizzle/GM_config/issues/64#issuecomment-75347058).

> I also get a blank page where I expected a demo.

[README.md](https://github.com/sizzlemctwizzle/GM_config/blob/master/README.md). Try a clean browser profile with no security restrictions e.g. possibly NoScript is at work... works for me at least once... although 2nd pass GH io seems to be doing something weird right now. :\

**Comment by Martii** [comment]
Ahh it's the brute force prevention on OUJS... we'll need to move the demo urls to GH for now.

**Comment by Martii** [comment]
Closed by https://github.com/sizzlemctwizzle/GM_config/commit/6cdf3b7c045d8d6ca0832009588ae84a2bca3ef9

**Comment by Martii** [comment]
@jesus2099 
Should be working full time now. Thanks for the report.

**Comment by jesus2099** [comment]
Great, @Martii, I do see it now indeed. :)
