### ISSUE TITLE
Dropdown box (type: 'select') appears empty when using {'value_1':'display_1','value_2':'display_2',...} in array options

### ISSUE THREAD

**Issue by darkred** [sizzlemctwizzle/GM_config#70]
I want to make a dropdown box (`type: 'select'`) in GM_config (using Greasemonkey) 
*(in order to further modify [this script](https://greasyfork.org/en/scripts/13846-thepiratebay-convert-dates-to-local-timezone))*.

This is the code:
```
GM_config.init('Settings',{
    choice:  { label: 'Choice:', section: ['Extras'], type: 'select', options: {'1':'Enhance','2': 'Hide', '3':'---'}, default: '1'  }     
},{
save: function(){location.reload();}});
```
and this is how it appears when clicking it: 
![image](https://i.imgur.com/WI7g1uE.jpg)

<br>
P.S. For reference, the following works ok:
```
GM_config.init('Settings',{
     enhanceVisibility:  { label: 'Choice:', section: ['Extras'], type: 'select', options: ['Enhance','Hide', '----'], default: 'Enhance' }   
},{
save: function(){location.reload();}});
```

**Comment by sizzlemctwizzle** [comment]
You are using outdated documentation. Use [the wiki](https://github.com/sizzlemctwizzle/GM_config/wiki). Here's the documentation for the select field type: https://github.com/sizzlemctwizzle/GM_config/wiki/Fields#select

**Comment by darkred** [comment]
Thank you for replying.
