### ISSUE TITLE
Please set up a GreasyFork entry for this

### ISSUE THREAD

**Issue by ssokolow** [sizzlemctwizzle/GM_config#71]
One of [GreasyFork](https://greasyfork.org/en)'s safety checks is to [whitelist](https://greasyfork.org/en/help/external-scripts) the domains where `@require` can point to in order to limit abuse. (Basically, it's limited to manually moderated CDNs and GreasyFork itself)

As a result, at least half a dozen different forks of your script have been posted as [libraries](https://greasyfork.org/en/scripts/libraries) there (often with no documentation because the poster only intended to use it in their own script).

Given that GreasyFork supports auto-syncing from Git repositories (either on a timer or via GitHub Webhook), would you mind creating a library entry on GreasyFork so there's an official entry people can use rather than posting yet another copy that won't receive updates?

(If your do something in your script that fails the static analysis, the sync will just stay on the last passing version until you push something that passes.)

**Comment by Martii** [comment]
@jasonbarnabe
Did you change the whitelisting of https://openuserjs.org/?library=true ?

@ssokolow 
This library is available at https://openuserjs.org/libs/sizzle/GM_config and I think it was whitelisted many months back when I was last reading on that site... unless he changed this.

**Comment by ssokolow** [comment]
Never mind. I must be tired but, somehow, I checked https://greasyfork.org/en/help/external-scripts twice and missed the https://openuserjs.org/?library=true entry both times.
