### ISSUE TITLE
GM_config Wiki page refers to deprecated GM_log

### ISSUE THREAD

**Issue by gerib** [sizzlemctwizzle/GM_config#74]
The first usage example contains `// @grant  GM_log`.

GM_log is [deprecated as of 11 November 2013](https://wiki.greasespot.net/index.php?title=GM_log&direction=next&oldid=4787).

**Comment by Martii** [comment]
This is kind of a duplicate for #59

When it is EOL'd it should go away but until then...

**Comment by janekptacijarabaci** [comment]
Ad SeaMonkey (i.e. 2.46a1): In `about:config`, `browser.dom.window.console.enabled` is default `false`.

And I note:
https://bugzilla.mozilla.org/show_bug.cgi?id=1136995#c5
https://bugzilla.mozilla.org/show_bug.cgi?id=860705

The Browser Console vs. The Web Console in future (probably):
GM_log = The Browser Console (for chrome content)
console.[something] = (only) The Web Console (for web content)

**Comment by sizzlemctwizzle** [comment]
Edit Message from revision [71c2519](https://github.com/sizzlemctwizzle/GM_config/wiki/Home/71c251944434bb1736d2be3e8147c8193a31a10e):
> We changed the code to prefer console.log over GM_log, so no need to recommend the ``@grant``.
