### ISSUE TITLE
How can I get the value of type:'select' correctly?

### ISSUE THREAD

**Issue by emrtop** [sizzlemctwizzle/GM_config#77]
Hey,

I have already tried `GM_config.get('valueName');` but it doesn't work.
`'valueName': {'label': 'Value', 'type': 'select', 'options': ['Hello', 'Hey', 'Hi'], 'default': 'Hey'},`
The output is "undefined".

Thanks for your help!

**Comment by Martii** [comment]
> How can I get the value of type:'select' correctly?

Take a look at the GM_config Unit Test at [this line](https://github.com/sizzlemctwizzle/UserScripts/blob/183028b05cbef7ceba28b1c9ca6668d77679d7b5/gm_config_unit_test.user.js#L267). Every setting has an example there. [The wiki](https://github.com/sizzlemctwizzle/GM_config/wiki) also has some information.

**Comment by Martii** [comment]
Additionally if you add the code to the tail of the Unit Test of:

``` js
alert(GM_config.get('work'));
```

It shows the last saved value. So something you may be doing is incorrect. Peruse over the Unit Test and support docs to try again. :)
