### ISSUE TITLE
How to sync the data between two webpage

### ISSUE THREAD

**Issue by leehin** [sizzlemctwizzle/GM_config#79]
I have two webpages open at the same time, sharing the same GM_config inside a common greasemonkey script. (the same greasemonkey script is executed for these two different pages)O
I change a gm_config field in the first webpage using GM_config.set('a','new value'),
When i use GM_config.open() on the second webpage, it still show the old value).
The second webpage only get the new value for that field when i refresh the second webpage. 
How do i propagate the changes so that the second webpage get the new value for that field without the need to refresh the second webpage

**Comment by sizzlemctwizzle** [comment]
The answer is in the wiki, section **[Customizing GM_config](https://github.com/sizzlemctwizzle/GM_config/wiki#customizing-gm_config)**
> However, although this sets the value of the field in memory, it won't save the value. You will need to call GM_config.save().

For even more advance use cases, see **[Remove and Reload fields in the GM_config panel](https://github.com/sizzlemctwizzle/GM_config/wiki/Advance-Fields#remove-and-reload-fields-in-the-gm_config-panel)**

The wiki is there to provide general support like this. Please read it.
