### ISSUE TITLE
[Feature Request] Add import/export

### ISSUE THREAD

**Issue by tomas-chrastina** [sizzlemctwizzle/GM_config#95]
Hello,

it would be nice to have also **file based import/export** feature alongside save,close and reset.

Thank you in advance for sonsidering this.

--
Best regards,
Tomas.

**Comment by sizzlemctwizzle** [comment]
This might be nice to have but could be done as easily by 3rd party code. If anyone does this and wants to share, I'd consider a pull request with the code in a separate file, but I'm closing since I don't want to make it part of GMC.
