### ISSUE TITLE
config.init frame option results in an error.

### ISSUE THREAD

**Issue by MisteryMan** [sizzlemctwizzle/GM_config#96]
Using the following init code:
`    GM_config.init(
        {
            'id': 'autoHideMissions', // The id used for this instance of GM_config
            'title': 'Auto Hide Missions',
            'fields': // Fields object
            {
                'greenStatus': // This is the id of the field
                {
                    'label': 'Green Status', // Appears next to field
                    'type': 'select', // Makes this setting a text field
                    'default': 'Nothing', // Default value if user doesn't change it
                    'options': ['Hidden', 'Collapse', 'Nothing']
                },
                'yellowStatus':
                {
                    'label': 'Yellow Status',
                    'type': 'select',
                    'default': 'Nothing',
                    'options': ['Hidden', 'Collapse', 'Nothing']
                }
            },
            'frame': 'autoMissionSettingFrame'
        }`

results in the following error when GM_config.open() is triggered:
`userscript.html?name=Autohide%20Missions.user.js&id=f6f58b4a-12e0-48c1-996f-7f3da7f0db64:314 Uncaught TypeError: this.frame.setAttribute is not a function
    at GM_configStruct.open (userscript.html?name=Autohide%20Missions.user.js&id=f6f58b4a-12e0-48c1-996f-7f3da7f0db64:314)
    at HTMLAnchorElement.eval (userscript.html?name=Autohide%20Missions.user.js&id=f6f58b4a-12e0-48c1-996f-7f3da7f0db64:869)
    at HTMLAnchorElement.dispatch (application-a1de7f890db71cf55a88756a3e0b68fc.js:28)
    at HTMLAnchorElement.g.handle (application-a1de7f890db71cf55a88756a3e0b68fc.js:28)`

**Comment by Martii** [comment]
How about with the [current HEAD](https://github.com/sizzlemctwizzle/GM_config/tree/43fd0fe4de1166f343883511e53546e87840aeaf) ?

If your issue is still present you need to provide more information about browser version and platform for retesting.

**Comment by sizzlemctwizzle** [comment]
dead issue, so closing now
